services:
  postgres:
    image: postgres:16-alpine
    container_name: bitemap_postgres
    environment:
      POSTGRES_USER: bitemap
      POSTGRES_PASSWORD: bitemap
      POSTGRES_DB: bitemap
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
